### ISSUE TITLE
Add message to radarr_system_health metric

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/radarr-exporter#10]
@rubasace Back to the health issues report in Radarr/Sonarr. I managed to test this out and the health issues are as described in the current metrics below. This is great and makes you check Sonarr/Radarr for the actual health issue and fix it.

```bash
# HELP sonarr_health_issues Amount of health issues in Sonarr
# TYPE sonarr_health_issues gauge
sonarr_health_issues{hostname="http://192.168.42.231:8989",type="error"} 1
sonarr_health_issues{hostname="http://192.168.42.231:8989",type="warning"} 2
```

On another note, since the API returns the follow json we can add `message` into the metric.

```json
[
  {
    "type": "warning",
    "message": "No indexers available with Automatic Search enabled, Sonarr will not provide any automatic search results",
    "wikiUrl": "https://github.com/Sonarr/Sonarr/wiki/Health-checks#no-indexers-available-with-automatic-search-enabled-sonarr-will-not-provide-any-automatic-search-results"
  },
  {
    "type": "warning",
    "message": "No download client is available",
    "wikiUrl": "https://github.com/Sonarr/Sonarr/wiki/Health-checks#no-download-client-is-available"
  },
  {
    "type": "error",
    "message": "No indexers available with RSS sync enabled, Sonarr will not grab new releases automatically",
    "wikiUrl": "https://github.com/Sonarr/Sonarr/wiki/Health-checks#no-indexers-available-with-rss-sync-enabled-sonarr-will-not-grab-new-releases-automatically"
  }
]
```

For example with `message` added...

```bash
# HELP sonarr_health_issues Amount of health issues in Sonarr
# TYPE sonarr_health_issues gauge
sonarr_health_issues{hostname="http://192.168.42.231:8989",type="error",message="No indexers available with RSS sync enabled, Sonarr will not grab new releases automatically"} 1
sonarr_health_issues{hostname="http://192.168.42.231:8989",type="warning", message="No indexers available with Automatic Search enabled, Sonarr will not provide any automatic search results"} 1
sonarr_health_issues{hostname="http://192.168.42.231:8989",type="warning", message="No download client is available"} 1
```

Do you think this is something we'd want to add? I guess if we want alert-manager or grafana alerting to actually display the message I would assume so.

**Comment by onedr0p** [comment]
Added in v1.2.4 :rocket:

**Comment by rubasace** [comment]
I think message would be too verbose and, also, it isn't really something we can anticipate so from the monitoring perspective it'd be useless IMO

**Comment by onedr0p** [comment]
ha, too late. I think it's fine though. I am going to be creating alert-manager rules with this information, and using the wikiurl as the runbook.

You'll be able to ignore message and wikiurl from the metric by just grabbing a count:

```
count(radarr_health_issues) by (type)
```

**Comment by rubasace** [comment]
Damn you are fast. Yep sure, I can grab them by type and ignore the message. Probably an alert rule on prometheus just `radarr_health_issues{type!="OK"}` will do better (still getting messages from the alert if I want on alertmanager). 
I like the runbook approach too, though I think it's a bit overkill for this scenarios, as usually it will just be one indexer/download client randomly down or some configuration error, but I think it's good to have the extra dimension so it's up to the user :)
