### ISSUE TITLE
radarr_movie_missing_total separation

### ISSUE THREAD

**Issue by dirtycajunrice** [onedr0p/radarr-exporter#11]
Hey! Glad someone decided to do sonarr/radarr exporters! Could you split missing/unavailable with missing/available?

**Comment by onedr0p** [comment]
Good idea, I'm current reworking these exporters to support v3 of the sonarr and radarr API. I'll work on this as well

**Comment by onedr0p** [comment]
@DirtyCajunRice actually I am think about this more and I don't really understand what you mean. Can you be a little more specific? Thanks!

**Comment by dirtycajunrice** [comment]
in radarr, when you query missing, you get missing that is unreleased, as well as missing that is released. many people are not interested in a missing metric they can do nothing about (the unreleased portion). I know this because im the creator of https://github.com/Boerderij/Varken and have done this whole dance just the python+influx way haha. If you use discord im DirtyCajunRice#0001

**Comment by onedr0p** [comment]
This is done, closing
