### ISSUE TITLE
Listen to any IP

### ISSUE THREAD

**Issue by falstaff1288** [onedr0p/radarr-exporter#17]
Hello, the application currently only listen to the localhost interface. Would it be possible to make it so that we can set the listening IP as we wish? (Since were at it, I have same request for sonarr-exporter). I plan to use this binary outside a container.

Cheers.

**Comment by onedr0p** [comment]
Hi @falstaff1288 I believe this should allow you to do that:

https://github.com/onedr0p/radarr-exporter/commit/2e5e671e782c331e5a53cfef8f61ac9d57dd1f16

If you are building from command line can you try it out?

**Comment by falstaff1288** [comment]
It's working but the service exits after one successful connection. BTW, I'm using a self-signed certificate. Here's the verbose msg from the log:

```
# Fake domain for this example;
FATA[0004] An error has occurred during retrieving Radarr statistics Get "https://radarr.example.com/api/v3/rootfolder": x509: certificate signed by unknown authority 
```

**Comment by onedr0p** [comment]
That's great!

Good catch, I will add an option to have SSL be ignored.

**Comment by onedr0p** [comment]
@falstaff1288 added a flag and envar to disable SSL verification, let me know if it works :)

https://github.com/onedr0p/radarr-exporter/commit/3397125a1ad5ffd384af5cc3a8fb5636eeba3d8a

**Comment by falstaff1288** [comment]
It's working but now I'm getting a different issue. 

I'll close this one since it's resolved. Thanks.

**Comment by onedr0p** [comment]
ok great! open another issue if you need help :)
