### ISSUE TITLE
FATA[0013] An error has occurred during retrieving Radarr statistics HTTP statuscode not 200

### ISSUE THREAD

**Issue by falstaff1288** [onedr0p/radarr-exporter#18]
Its as the title says.

```
$ ./radarr-exporter start --url https://radarr.example.com --api-key "XXXXXXXXXXXXXXXXXXXXX" --listen-ip 0.0.0.0 --disable-ssl-verify --log-level "TRACE"
INFO[0000] Listening on 0.0.0.0:9707                    
DEBU[0013] 192.168.1.10:40706 GET /metrics              
INFO[0013] Sending HTTP request to https://radarr.example.com/api/v3/history 
INFO[0013] Sending HTTP request to https://radarr.example.com/api/v3/rootfolder 
INFO[0013] Sending HTTP request to https://radarr.example.com/api/v3/system/status 
INFO[0013] Sending HTTP request to https://radarr.example.com/api/v3/health 
INFO[0013] Sending HTTP request to https://radarr.example.com/api/v3/movie 
INFO[0013] Sending HTTP request to https://radarr.example.com/api/v3/queue?page=1&includeUnknownMovieItems=true 
FATA[0013] An error has occurred during retrieving Radarr statistics HTTP statuscode not 200 
```
I tested an API call withthis  cURL example [found in this link](https://github.com/Radarr/Radarr/wiki/API) and it works.
```
curl -d '{name: "missingMoviesSearch", filterKey: "status", filterValue: "released"}' -H "Content-Type: application/json" -X POST http://RADARRIP:RADARRPORT/api/command?apikey=RADARRAPIKEY
```
BTW, my Radarr service is behind a Proxy (Caddy). The return HTTP code is 201.

```
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 201 
< access-control-allow-origin: *
< cache-control: no-cache, no-store, must-revalidate
< content-type: application/json; charset=utf-8
< date: Sun, 12 Apr 2020 00:11:06 GMT
< expires: 0
< pragma: no-cache
< server: Caddy
< server: Mono-HTTPAPI/1.0
< x-applicationversion: 0.2.0.1480
< content-length: 548
```

Sorry for all the edits :p

**Comment by onedr0p** [comment]
haha another nice catch! I'll just check for any valid status code 2xx or 3xx :)

**Comment by onedr0p** [comment]
Give this one a try, here's the commit

https://github.com/onedr0p/radarr-exporter/commit/5bc045b5959e9048c77ce5a4de5a41d810b225a9

**Comment by falstaff1288** [comment]
Still not working. I saw your latest commit 1c1fc1fe ; this is the error I'm getting:

```
FATA[0009] An error has occurred during retrieving Radarr statistics HTTP statuscode 404
```

**Comment by onedr0p** [comment]
404, hm. That makes me think you are not using radarr v3, or something else weird on your end.

Radarr uses a new api endpoint in v3, see if that works.

```
curl "https://radarr.yourdomain/api/v3/movies" \
     -H 'X-Api-Key: yourapikey'
```

I dropped support for Radarr v2 API awhile ago.

**Comment by falstaff1288** [comment]
Result of the curl command:
```
{
  "message": "NotFound"
}
```
BTW, I'm using the version `0.2.0.1480` of Radarr.

**Comment by onedr0p** [comment]
I dropped support for Radarr v2 API after [v1.2.5](https://github.com/onedr0p/radarr-exporter/releases/tag/v1.2.5) of this exporter. I don't really suggest upgrading to Radarr v3 BUT it is really great and worth trying out. Make sure you take backups if you want to try.

**Comment by falstaff1288** [comment]
I see, you're using the "aphrodite" version of Radarr which is still in development. 

I'll stick with the v2 for now. Maybe to mention this little detail in the README.


Thanks again for your help!

**Comment by onedr0p** [comment]
I'll make sure to do that. If you back up your radarr data directory you should be able to try Aphrodite out without trouble. I don't want to give you bad advice in trying out the new version in case something goes wrong. But I've been running it for 4 months without issue. You may not want to go back, the new UI is beautiful.

**Comment by falstaff1288** [comment]
Just installed aphrodite. It sure looks nice :)

And the exporter is working fine.

**Comment by onedr0p** [comment]
haha, nice! Make sure you set your backups to daily in the Settings.

**Comment by falstaff1288** [comment]
Done. Thanks again.

**Comment by onedr0p** [comment]
@falstaff1288 I am merging these exporters into one project for better maintainability. I would love some feedback. Feel free to reach out to me via discord

onedr0p#6357

Edit forgot link:

https://github.com/onedr0p/exportarr

**Comment by falstaff1288** [comment]
Interesting! Will look into this new project in the coming days.

**Comment by falstaff1288** [comment]
Also: I was starting to create a PKGBUILD manifest in order to add radarr-exporter in the AUR for ArchLinux. Might do it instead with exportarr.

**Comment by onedr0p** [comment]
That would be excellent!
