### ISSUE TITLE
Add Grafana dashboard

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/radarr-exporter#4]
Add a Grafana dashboard to this repo to share with community.

**Comment by onedr0p** [comment]
I got this done, I am going to tweak it more before I post it

![image](https://user-images.githubusercontent.com/213795/78461976-c6784280-769b-11ea-8cee-40fe8f13da71.png)

**Comment by buzzke** [comment]
Nice.  Please share the dashboard after completion

**Comment by onedr0p** [comment]
@buzzke I sure will! I think the exporter is in a stable spot to post this.

**Comment by onedr0p** [comment]
added here

https://github.com/onedr0p/radarr-exporter/tree/master/examples/grafana
